version: '3'

services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: workspace
    ports:
      - ${VITE_PREVIEW_HOST:-127.0.0.1}:${VITE_PREVIEW_PORT:-4173}:4173 # Vite preview
      - ${VITE_DEV_HOST:-127.0.0.1}:${VITE_DEV_PORT:-5173}:5173 # Vite dev
      - ${PLAYWRIGHT_HTML_REPORT_HOST:-127.0.0.1}:${PLAYWRIGHT_HTML_REPORT_PORT:-9323}:9323 # Playwright HTML report
      - ${VITEST_UI_HOST:-127.0.0.1}:${VITEST_UI_PORT:-51204}:51204
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      CONTAINER: 1
    command: sleep infinity
    init: true
