<script lang="ts">
	import type { TreeNode } from '$lib/toc';
	import TocTree from './TocTree.svelte';

	interface Props {
		tree: TreeNode<HTMLElement>;
		activeId?: string;
		[key: string]: any;
	}

	let { tree, activeId = '', ...rest }: Props = $props();

	const heading = $derived(tree.data.textContent);

	// Link possibly generated by rehype-slug
	let link = $derived(tree.data.querySelector('a')?.getAttribute('href') || '');
	const isActive = $derived(link && activeId && link === activeId);

	// Add styling based on heading level
	let tagName = $derived(tree.data.tagName.toLowerCase());
	let fontClass = $derived(
		tagName === 'h1' || tagName === 'h2'
			? 'font-semibold text-base'
			: tagName === 'h3'
				? 'font-medium text-sm'
				: 'font-light text-sm text-gray-500'
	);
</script>

<div data-testid="toc-tree" class="text-center lg:text-left" {...rest}>
	<p class="mb-1.5 {fontClass}">
		<a
			class={isActive ? 'link-hover link text-secondary font-bold underline' : 'link-hover link'}
			href={link}>{heading}</a
		>
	</p>
	<ul>
		{#each tree.children as child (child.data.textContent)}
			<li class="lg:ml-8">
				<TocTree tree={child} {activeId} />
			</li>
		{/each}
	</ul>
</div>
