<script lang="ts">
	import type { TreeNode } from '$lib/toc';
	import TocTree from './TocTree.svelte';

	interface Props {
		tree: TreeNode<HTMLElement>;
		activeId?: string;
		[key: string]: any;
	}

	let { tree, activeId = '', ...rest }: Props = $props();

	const heading = $derived(tree.data.textContent);

	// Link possibly generated by rehype-slug
	const link = $derived(tree.data.querySelector('a')?.getAttribute('href') || '');
	const isActive = $derived(link && activeId && link === activeId);
</script>

<div data-testid="toc-tree" {...rest}>
	<p class="mb-1.5 font-light">
		<a class={isActive ? 'link-hover link font-bold underline text-secondary' : 'link-hover link'} href={link}>{heading}</a>
	</p>
	<ul>
		{#each tree.children as child (child.data.textContent)}
			<li class="ml-8">
				<TocTree tree={child} {activeId} />
			</li>
		{/each}
	</ul>
</div>
