<script lang="ts">
	import type { TreeNode } from '$lib/toc';
	import TocTree from './TocTree.svelte';

	interface Props {
		tree: TreeNode<HTMLElement>;
		activeId?: string;
		isHovered?: boolean;
	}

	let { tree, activeId = '', isHovered = false }: Props = $props();

	const heading = $derived(tree.data.textContent);

	// Link possibly generated by rehype-slug
	let link = $derived(tree.data.querySelector('a')?.getAttribute('href') || '');
	const isActive = $derived.by(() => {
		if (!link || !activeId) return false;
		if (link === activeId) return true;
		try {
			return decodeURIComponent(link) === decodeURIComponent(activeId);
		} catch {
			return false;
		}
	});

	// Add styling based on heading level
	let tagName = $derived(tree.data.tagName.toLowerCase());

	// Line styling for idle floating state
	let lineWidthClass = $derived(
		tagName === 'h1' || tagName === 'h2' ? 'w-6' : tagName === 'h3' ? 'w-4' : 'w-2.5'
	);

	let lineIndentClass = $derived(
		tagName === 'h1' || tagName === 'h2' ? 'ml-0' : tagName === 'h3' ? 'ml-2' : 'ml-4'
	);
</script>

{#if !isHovered}
	<div data-testid="toc-tree" class="flex flex-col items-start {lineIndentClass} my-1">
		<div
			class="h-1 {lineWidthClass} rounded-full transition-all duration-200 {isActive
				? 'bg-secondary h-1.5 shadow-xs'
				: 'bg-base-content/25'}"
		></div>
	</div>
	{#each tree.children as child (child.data.textContent)}
		<TocTree tree={child} {activeId} {isHovered} />
	{/each}
{:else}
	<div data-testid="toc-tree" class="text-left">
		<a
			class="block overflow-hidden py-1.5 text-sm text-ellipsis whitespace-nowrap transition-colors {isActive
				? 'text-primary font-bold'
				: 'text-base-content/70 hover:text-base-content'} {tagName === 'h1' || tagName === 'h2'
				? 'mt-2 text-base font-semibold'
				: ''}"
			href={link}
		>
			{heading}
		</a>
		{#if tree.children.length > 0}
			<ul class="border-base-200/60 ml-3 border-l-2 pl-3">
				{#each tree.children as child (child.data.textContent)}
					<li>
						<TocTree tree={child} {activeId} {isHovered} />
					</li>
				{/each}
			</ul>
		{/if}
	</div>
{/if}
