name: GitHub Pages

on:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
