name: Release

on:
  push:
    tags:
      - v*

permissions: read-all

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install PNPM deps
        run: pnpm install

      - name: Build site
        run: pnpm run build
        env:
          VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          path: build/

  deploy:
    name: Deploy
    needs:
      - release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  lighthouse:
    name: Lighthouse
    needs:
      - deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          runs: 3
          configPath: ./.lighthouserc.json
          budgetPath: ./budget.json
          urls: |
            ${{ needs.deploy.outputs.page_url }}/
            ${{ needs.deploy.outputs.page_url }}/about-me
            ${{ needs.deploy.outputs.page_url }}/blog
          temporaryPublicStorage: true
